name: Auto fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  # issues: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 22
      PNPM_VERSION: 9

    steps:
      - uses: actions/checkout@v4

      - name: Deps cache (restore)
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ./node_modules
            ~/.pnpm
          key: pnpm-v${{ env.PNPM_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-v${{ env.PNPM_VERSION }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          #cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Switch branch
        run: git switch -c autofix-${{ github.sha }}

      - name: Lint (Biome)
        run: pnpm run lint:write

      #- name: Format (Biome)
      #  run: pnpm run format:write

      - name: Git
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto format"
            git push -u origin autofix-${{ github.sha }}

            gh pr create --base ${{ github.ref_name }} --title "Auto format" --body ""
          fi
