name: Auto fix

on:
  workflow_dispatch:
    inputs:
      unsafe:
        type: boolean
        required: false
        description: 'Apply unsafe changes'
        default: false

permissions:
  contents: write
  pull-requests: write
  # issues: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 22
      PNPM_VERSION: 9

    steps:
      - uses: actions/checkout@v4

      - name: Deps cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ~/.local/share/pnpm/store
          key: pnpm-v${{ env.PNPM_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-v${{ env.PNPM_VERSION }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          #cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Unsafe setting
        id: unsafe
        if: ${{ inputs.unsafe }}
        run: |
          echo 'arg=--unsafe' >> $GITHUB_OUTPUT

      - name: Switch branch
        run: git switch -c autofix-${{ github.sha }}

      - name: Biome
        id: biome
        shell: /usr/bin/bash {0}
        run: |
          pnpm exec biome check --write ${{ steps.unsafe.outputs.arg }}
          echo 'status=$?' >> $GITHUB_OUTPUT

      - name: Git
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto format"
            git push -u origin autofix-${{ github.sha }}

            echo "## Note" >> /tmp/pr_body
            echo >> /tmp/pr_body
            if [ "${{ inputs.unsafe }}" = "true" ]; then
              echo "- Contains unsafe changes" >> /tmp/pr_body
            elif [ "${{ steps.biome.outputs.status }}" -ne 0 ]; then
              echo "- Incomplete fix" >> /tmp/pr_body
            else
              echo "nothing to write" >> /tmp/pr_body
            fi

            echo >> /tmp/pr_body
            echo "## Log:" >> /tmp/pr_body
            echo >> /tmp/pr_body
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> /tmp/pr_body

            gh pr create --base ${{ github.ref_name }} --title "Auto format" --body-file /tmp/pr_body
          fi
